language: node_js
node_js:
  - "4"
  - "5"
  - "6"

before_script:
  - npm install
  - mysql -e 'create database yodel_test;'
  - cp .env.sample .env.test
  - NODE_ENV=test tasks/migrate

services:
  - redis-server
  - mysql
